services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Ufo\EAV\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UfoEAVBundle.php'
            - '../src/Entity/'

    Ufo\EAV\EventsSubscribers\EmptyProductSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Ufo\EAV\EventsSubscribers\RemoveSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Ufo\EAV\EventsSubscribers\SchemaGenerateSubscriber:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
    
    Ufo\EAV\EventsSubscribers\ResolveTargetEntitySubscriber:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
            - { name: doctrine.event_listener, event: loadClassMetadata }

    Ufo\EAV\Fillers\Interfaces\IFiller $allSpecsFiller: '@Ufo\EAV\Fillers\AllSpecsFiller'
    Ufo\EAV\Fillers\Interfaces\IFiller $filteredSpecsFiller: '@Ufo\EAV\Fillers\FilteredSpecsFiller'

    Ufo\EAV\Services\LocaleService:
        arguments:
            $defaultLocale: '%kernel.default_locale%'
#            $localeAwareServices: '@Symfony\Component\Translation\LocaleSwitcher'
    
 